name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-fractal-cloud-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.x'
      - name: Install dependencies for Fractal Cloud SDK
        run: |
          npm install
      - name: Build Fractal Cloud SDK
        run: |
          npm run build
      - name: Run Unit Tests for Fractal Cloud SDK
        run: |
          npm run test
